name: Python package

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OpenMC
      run: |
        sudo apt-get install -y g++ cmake libhdf5-dev
        git clone --recurse-submodules https://github.com/openmc-dev/openmc.git
        cd openmc
        git checkout
        mkdir build && cd build
        cmake ..
        make
        sudo make install
    - name: Install plasma source
      run: |
        pip install -r requirements-develop.txt
        python setup.py bdist_wheel
        python -m pip install --verbose dist/*.whl
    - name: Run tests
      run: |
        pytest tests
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
