name: Python package

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenMC
      run: |
        yum install -y gcc-c++ cmake3 hdf5-devel
        alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 20 \
        --slave /usr/local/bin/ctest ctest /usr/bin/ctest3 \
        --slave /usr/local/bin/cpack cpack /usr/bin/cpack3 \
        --slave /usr/local/bin/ccmake ccmake /usr/bin/ccmake3 \
        --family cmake
        git clone --recurse-submodules https://github.com/openmc-dev/openmc.git
        cd openmc
        git checkout
        mkdir build && cd build
        cmake ..
        make
        make install
    - name: Install plasma source
      run: |
        export PYVER=${{ matrix.python-version }}
        alias python=$(ls -d /opt/python/* | grep ${PYVER//.})/bin/python
        python -m pip install -r requirements-develop.txt
        python -m pip install auditwheel
        python setup.py bdist_wheel
        python -m auditwheel show dist/*.whl
        python -m auditwheel repair dist/*.whl
        python -m pip install --verbose wheelhouse/*.whl
    - name: Run tests
      run: |
        export PYVER=${{ matrix.python-version }}
        alias python=$(ls -d /opt/python/* | grep ${PYVER//.})/bin/python
        cd tests
        python -m pytest
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: wheelhouse
    - name: Publish wheel artifact
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
    run: |
        export PYVER=${{ matrix.python-version }}
        alias python=$(ls -d /opt/python/* | grep ${PYVER//.})/bin/python
        python -m pip install twine
        python -m twine upload --repository testpypi wheelhouse/*
